
const DATA_PATH='data/site-data.json';
let DATA=null;
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const num=(v,d=1)=>Number.isFinite(Number(v))?Number(v).toFixed(d):'—';
const badge=(t,c='info')=>`<span class="badge ${c}">${esc(t)}</span>`;
const ratingClass=r=>/good/i.test(r)?'good':/poor|critical/i.test(r)?'bad':'warn';
async function load(){const res=await fetch(DATA_PATH,{cache:'no-store'}); if(!res.ok) throw new Error('Cannot load data/site-data.json'); DATA=await res.json(); return DATA;}
function nav(active){return `<div class="topbar"><div class="nav"><div class="brand">Saadiyat Lagoons HSE<small>Performance & Action Portal</small></div>${[['index.html','Dashboard'],['cluster-performance.html','Cluster Performance'],['capa.html','CAPA'],['gap-analysis.html','Gap Analysis']].map(([h,l])=>`<a class="${active===h?'active':''}" href="${h}">${l}</a>`).join('')}</div></div>`}
function shell(active,title,sub){document.body.insertAdjacentHTML('afterbegin',nav(active)); $('#app').innerHTML=`<main class="container"><section class="hero"><h1>${title}</h1><p>${sub||''}</p></section><div id="content"></div><div class="footer">Cluster 3, 4, 5 and 6 data removed from all dashboard calculations.</div></main>`; return $('#content');}
function table(headers, rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c??''}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function chartOptions(){return {responsive:true,maintainAspectRatio:false,animation:false,plugins:{legend:{labels:{color:'#dce9f7'}}},scales:{x:{ticks:{color:'#b8c9df'},grid:{color:'rgba(148,184,255,.08)'}},y:{ticks:{color:'#b8c9df'},grid:{color:'rgba(148,184,255,.08)'}}}}}
function barColor(v){v=Number(v); if(!Number.isFinite(v)) return 'rgba(120,140,165,.65)'; if(v>=75||v>=3.5&&v<=5) return '#23c483'; if(v>=60||v>=2.5&&v<=5) return '#f3bd4f'; return '#ff6b7a'}
function renderDashboard(){const c=shell('index.html','HSE Performance Dashboard','Professional overview for active Saadiyat Lagoons clusters only.'); const inspections=DATA.inspections||[], clusters=DATA.clusters||[], kpis=DATA.kpis||[]; const avg=clusters.length?clusters.reduce((s,x)=>s+(Number(x.avgScore)||0),0)/clusters.length:0; const red=clusters.reduce((s,x)=>s+(Number(x.redFlags)||0),0); c.innerHTML=`<div class="notice">Data check completed: Cluster 3, Cluster 4, Cluster 5 and Cluster 6 have been removed.</div><div class="grid cards section"><div class="card stat"><div class="label">Active Inspections</div><div class="value">${inspections.length}</div><div class="hint">Filtered records</div></div><div class="card stat"><div class="label">Active Clusters</div><div class="value">${clusters.length}</div><div class="hint">Packages 2 & 4 focus</div></div><div class="card stat"><div class="label">Average Score</div><div class="value">${num(avg,1)}%</div><div class="hint">Cluster average</div></div><div class="card stat"><div class="label">Red Flags</div><div class="value">${red}</div><div class="hint">Critical follow-up</div></div></div><div class="grid two section"><div class="card"><h2 class="section-title">Cluster Performance</h2><div class="chart-box"><canvas id="clusterChart"></canvas></div></div><div class="card"><h2 class="section-title">Lowest KPI Averages</h2><div class="chart-box"><canvas id="kpiChart"></canvas></div></div></div><div class="card section"><h2 class="section-title">Cluster Summary</h2>${table(['Package','Cluster','Inspections','Avg Score','Red Flags','Rating'], clusters.map(x=>[esc(x.package),esc(x.cluster),x.inspections,num(x.avgScore,1)+'%',x.redFlags,badge(x.rating,ratingClass(x.rating))]))}</div>`; new Chart($('#clusterChart'),{type:'bar',data:{labels:clusters.map(x=>x.cluster),datasets:[{label:'Average Score %',data:clusters.map(x=>x.avgScore),backgroundColor:clusters.map(x=>barColor(x.avgScore)),borderWidth:0}]},options:chartOptions()}); new Chart($('#kpiChart'),{type:'bar',data:{labels:kpis.slice(0,10).map(x=>x.kpi),datasets:[{label:'KPI Avg / 5',data:kpis.slice(0,10).map(x=>x.avg),backgroundColor:kpis.slice(0,10).map(x=>barColor(x.avg)),borderWidth:0}]},options:{...chartOptions(),indexAxis:'y'}});}
function renderCluster(){const c=shell('cluster-performance.html','Cluster Performance','Cluster-by-cluster scoring and red flag view.'); const clusters=DATA.clusters||[]; c.innerHTML=`<div class="grid two"><div class="card"><h2 class="section-title">Average Score by Cluster</h2><div class="chart-box tall"><canvas id="scoreChart"></canvas></div></div><div class="card"><h2 class="section-title">Red Flags by Cluster</h2><div class="chart-box tall"><canvas id="redChart"></canvas></div></div></div><div class="card section"><h2 class="section-title">Details</h2>${table(['Package','Cluster','Inspections','Average Score','Open Actions','Red Flags','Rating'],clusters.map(x=>[esc(x.package),esc(x.cluster),x.inspections,num(x.avgScore,1)+'%',x.openActions,x.redFlags,badge(x.rating,ratingClass(x.rating))]))}</div>`; new Chart($('#scoreChart'),{type:'bar',data:{labels:clusters.map(x=>x.cluster),datasets:[{label:'Average Score %',data:clusters.map(x=>x.avgScore),backgroundColor:clusters.map(x=>barColor(x.avgScore))}]},options:chartOptions()}); new Chart($('#redChart'),{type:'bar',data:{labels:clusters.map(x=>x.cluster),datasets:[{label:'Red Flags',data:clusters.map(x=>x.redFlags),backgroundColor:'#ff6b7a'}]},options:chartOptions()});}
function renderCapa(){const c=shell('capa.html','CAPA Tracker','Corrective and preventive actions from active clusters only.'); const rows=DATA.capa||[]; c.innerHTML=`<div class="card"><h2 class="section-title">CAPA Actions</h2>${table(['Date','Cluster','Activity','Root Cause','Immediate Action','Preventive Action','Owner','Target'],rows.map(x=>[esc(x.date),esc(x.cluster),esc(x.activity),esc(x.rootCause),esc(x.immediate),esc(x.preventive),esc(x.owner),esc(x.targetDate)]))}</div>`;}
function renderGaps(){const c=shell('gap-analysis.html','Gap Analysis','Most repeated gaps after removing Cluster 3, 4, 5 and 6 data.'); const gaps=DATA.gaps||[], kpis=DATA.kpis||[]; c.innerHTML=`<div class="grid two"><div class="card"><h2 class="section-title">Repeated Gaps</h2><div class="chart-box tall"><canvas id="gapChart"></canvas></div></div><div class="card"><h2 class="section-title">KPI Average Ranking</h2><div class="chart-box tall"><canvas id="allKpiChart"></canvas></div></div></div><div class="card section"><h2 class="section-title">Gap Table</h2>${table(['Gap','Count'],gaps.map(x=>[esc(x.gap),x.count]))}</div>`; new Chart($('#gapChart'),{type:'bar',data:{labels:gaps.map(x=>x.gap),datasets:[{label:'Count',data:gaps.map(x=>x.count),backgroundColor:'#62a8ff'}]},options:{...chartOptions(),indexAxis:'y'}}); new Chart($('#allKpiChart'),{type:'bar',data:{labels:kpis.map(x=>x.kpi),datasets:[{label:'Average / 5',data:kpis.map(x=>x.avg),backgroundColor:kpis.map(x=>barColor(x.avg))}]},options:{...chartOptions(),indexAxis:'y'}});}
function fail(e){document.body.innerHTML=`<div class="container"><div class="card"><h2>Dashboard failed to load</h2><p>${esc(e.message)}</p><p>Please confirm folders are exactly: assets/styles.css, scripts/app.js, data/site-data.json</p></div></div>`}
load().then(()=>{const p=location.pathname.split('/').pop()||'index.html'; if(p==='cluster-performance.html') renderCluster(); else if(p==='capa.html') renderCapa(); else if(p==='gap-analysis.html') renderGaps(); else renderDashboard();}).catch(fail);
