
const DATA_PATH='data/site-data.json';
async function loadData(){const res=await fetch(DATA_PATH);return await res.json();}
function pct(v){if(v===null||v===undefined||v==='')return '—';return `${(v*100).toFixed(1)}%`;}
function num(v,d=1){if(v===null||v===undefined||v==='')return '—';return Number(v).toFixed(d);}
function esc(v){if(v===null||v===undefined)return '';return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');}
function nl(v){return esc(v).replace(/\n/g,'<br>');}
function badge(text,type='info'){return `<span class="badge ${type}">${esc(text??'—')}</span>`;}
function scoreClass(v){if(v===null||v===undefined||v==='')return 'mid';const n=Number(v);if(n>=3.5)return 'high';if(n>=2.5)return 'mid';return 'low';}
function ratingBadge(r){const m={'Good':'good','Needs Improvement':'warn','Poor':'bad','Critical':'critical'};return badge(r||'—',m[r]||'info');}
function redFlagBadge(v){return String(v).toUpperCase()==='YES'?badge('Red Flag','critical'):badge('No','good');}
function nav(active){const items=[['index.html','Dashboard'],['inspections.html','Weekly Inspections'],['capa.html','CAPA'],['gap-analysis.html','Gap Analysis'],['schedules.html','Schedules'],['raw-data.html','All Sheets']];return `<div class="topbar"><div class="container"><div class="nav"><div class="brand">Saadiyat HSE Portal<small>Excel-to-website system</small></div>${items.map(([h,l])=>`<a href="${h}" class="${active===h?'active':''}">${l}</a>`).join('')}</div></div></div>`;}
function shell(active,title,sub){document.body.insertAdjacentHTML('afterbegin',nav(active));const root=document.getElementById('app');root.innerHTML=`<div class="container"><div class="hero"><div class="page-title"><div><h1>${title}</h1><p>${sub}</p></div></div></div><div id="content"></div><div class="footer">Prepared from the uploaded workbook. Weighted score fields in the source workbook contain broken references, so the website uses Raw Score % and all individual KPI fields.</div></div>`;return document.getElementById('content');}
function renderTable(container,headers,rows){container.innerHTML += `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c??''}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function buildDashboard(data){const c=shell('index.html','Full Aldar-style HSE Dashboard',`Selected week ${data.meta.selectedWeek} · Selected month ${data.meta.selectedMonth} · ${data.meta.inspectionCount} inspection records loaded`);
const avgRaw=data.weeklyInspections.reduce((a,r)=>a+(Number(r['Raw_Score_%'])||0),0)/Math.max(data.weeklyInspections.length,1);
const monthRows=data.weeklyInspections.filter(r=>r.Month===data.meta.selectedMonth);
const monthAvg=monthRows.reduce((a,r)=>a+(Number(r['Raw_Score_%'])||0),0)/Math.max(monthRows.length,1);
const redFlags=data.weeklyInspections.filter(r=>String(r.Critical_Red_Flag).toUpperCase()==='YES').length;
c.innerHTML += `<div class="note">${data.meta.notes.map(n=>`<div>• ${esc(n)}</div>`).join('')}</div><div class="section grid cards"><div class="card"><h3>Total Inspections</h3><div class="metric">${data.meta.inspectionCount}</div></div><div class="card"><h3>Selected Month Avg Raw</h3><div class="metric">${pct(monthAvg)}</div></div><div class="card"><h3>All Records Avg Raw</h3><div class="metric">${pct(avgRaw)}</div></div><div class="card"><h3>Critical Red Flags</h3><div class="metric">${redFlags}</div></div><div class="card"><h3>Open CAPA Actions</h3><div class="metric">${data.capa.length}</div></div><div class="card"><h3>Overdue CAPA</h3><div class="metric">${data.capa.filter(x=>x.Overdue_Flag==='YES').length}</div></div></div><div class="section"><h2>KPI Cards</h2><div class="grid kpi-grid">${data.gapAnalysis.kpis.map(k=>`<div class="card kpi-card"><div class="label">${esc(k.label)}</div><div class="score">${num(k.monthAvg)}</div><div class="small">Month avg / 5</div><div class="bar"><span style="width:${((k.monthAvg||0)/5)*100}%"></span></div><div class="small" style="margin-top:8px">Week avg ${num(k.weekAvg)} · Gap to 5: ${num(k.monthGapTo5)}</div></div>`).join('')}</div></div><div class="section grid two-col"><div class="card chart-card"><h2>Cluster Performance Comparison</h2><canvas id="clusterChart"></canvas></div><div class="card chart-card"><h2>KPI Average Comparison</h2><canvas id="kpiChart"></canvas></div></div><div class="section"><h2>Red Flag Heatmap by Cluster</h2><div class="table-wrap"><table class="heat"><thead><tr><th>Cluster</th>${data.gapAnalysis.kpis.map(k=>`<th>${esc(k.label)}</th>`).join('')}</tr></thead><tbody>${data.heatmap.map(r=>`<tr><td><b>${esc(r.cluster)}</b></td>${data.gapAnalysis.kpis.map(k=>{const v=r[k.field];return `<td><span class="score ${scoreClass(v)}">${v===null||v===undefined?'—':Number(v).toFixed(1)}</span></td>`;}).join('')}</tr>`).join('')}</tbody></table></div></div><div class="section"><h2>Latest Inspection Records</h2><div id="latestTable"></div></div>`;
renderTable(document.getElementById('latestTable'),['Date','Cluster','Area / Villa','Main Activity','Raw Score','Red Flag','Rating'],data.weeklyInspections.slice().sort((a,b)=>String(b.Inspection_Date).localeCompare(String(a.Inspection_Date))).map(r=>[esc(r.Inspection_Date),esc(r.Cluster),esc(r.Area_or_Villa),esc(r.Main_High_Risk_Activity),pct(r['Raw_Score_%']),redFlagBadge(r.Critical_Red_Flag),ratingBadge(r.Rating_Band)]));
new Chart(document.getElementById('clusterChart'),{type:'bar',data:{labels:data.weeklyDashboard.clusters.map(c=>c.cluster),datasets:[{label:'Week Avg Raw %',data:data.weeklyDashboard.clusters.map(c=>c.weekAvgRawPct?c.weekAvgRawPct*100:null)},{label:'Month Avg Raw %',data:data.weeklyDashboard.clusters.map(c=>c.monthAvgRawPct?c.monthAvgRawPct*100:null)}]},options:{responsive:true,plugins:{legend:{labels:{color:'#dce9f7'}}},scales:{x:{ticks:{color:'#bfd2e9'}},y:{ticks:{color:'#bfd2e9'}}}}});
new Chart(document.getElementById('kpiChart'),{type:'radar',data:{labels:data.gapAnalysis.kpis.map(k=>k.label),datasets:[{label:'Selected Week',data:data.gapAnalysis.kpis.map(k=>k.weekAvg)},{label:'Selected Month',data:data.gapAnalysis.kpis.map(k=>k.monthAvg)}]},options:{responsive:true,plugins:{legend:{labels:{color:'#dce9f7'}}},scales:{r:{angleLines:{color:'rgba(255,255,255,.14)'},grid:{color:'rgba(255,255,255,.14)'},pointLabels:{color:'#bfd2e9'},ticks:{display:false},suggestedMin:0,suggestedMax:5}}}});
}
function buildInspections(data){const c=shell('inspections.html','Weekly Inspection Records','Full inspection records with all KPI fields from the workbook');c.innerHTML += `<div class="filters"><input id="q" placeholder="Search cluster, area, activity..." /><select id="clusterFilter"><option value="">All clusters</option>${data.meta.clusters.map(cl=>`<option>${esc(cl)}</option>`).join('')}</select><select id="redFlagFilter"><option value="">All red flag status</option><option>YES</option><option>NO</option></select></div><div id="inspectionTable"></div>`;const headers=['Date','Week','Package','Cluster','Area / Villa','Activity','Stop Work','WAH','Edge','Falling','Excavation','Scaffold','PTW Impl','PTW Verify','MSRA','Lifting','Traffic','Housekeeping','Welfare','Fire','Supervision','Electrical','Raw %','Red Flag','Rating','Root Cause','Top Gaps','Immediate Action','Preventive Action'];const holder=document.getElementById('inspectionTable');function draw(){const q=document.getElementById('q').value.toLowerCase();const cluster=document.getElementById('clusterFilter').value;const red=document.getElementById('redFlagFilter').value;const rows=data.weeklyInspections.filter(r=>{const t=JSON.stringify(r).toLowerCase();return (!q||t.includes(q))&&(!cluster||r.Cluster===cluster)&&(!red||String(r.Critical_Red_Flag).toUpperCase()===red);}).map(r=>[esc(r.Inspection_Date),esc(r.Week_No),esc(r.Package),esc(r.Cluster),esc(r.Area_or_Villa),esc(r.Main_High_Risk_Activity),esc(r.Stop_Work||'—'),num(r.Work_at_Height),num(r.Edge_Protection),num(r.Falling_Object_Prevention),esc(r.Excavation_Safety),num(r.Scaffolding_Compliance),num(r.PTW_Implementation),num(r.PTW_Field_Verification),esc(r.MSRA_Quality),num(r['Lifting/Precast Installation']),num(r.Traffic_Interface),num(r['Housekeeping/Waste Management']),num(r['Welfare Arrangement']),num(r.Fire_Readiness),num(r.Supervision_Subcontractor),num(r.Electrical_Tool_Safety),pct(r['Raw_Score_%']),redFlagBadge(r.Critical_Red_Flag),ratingBadge(r.Rating_Band),esc(r.Likely_Root_Cause),`<div class="pre">${nl(r.Top_3_Gaps_Observed)}</div>`,`<div class="pre">${nl(r.Immediate_Action_Taken)}</div>`,`<div class="pre">${nl(r.Preventive_Action_Required)}</div>`]);holder.innerHTML='';renderTable(holder,headers,rows);}draw();['q','clusterFilter','redFlagFilter'].forEach(id=>document.getElementById(id).addEventListener('input',draw));}
function buildCapa(data){const c=shell('capa.html','CAPA Tracking System','Corrective and preventive actions built from inspection findings');c.innerHTML += `<div id="capaTable"></div>`;renderTable(document.getElementById('capaTable'),['Action ID','Date Raised','Cluster','Package','KPI Area','Root Cause','Finding','Immediate Action','Preventive Action','Owner','Target','Overdue'],data.capa.map(r=>[esc(r.Action_ID),esc(r.Date_Raised),esc(r.Cluster),esc(r.Package),esc(r.KPI_Area),esc(r.Root_Cause),`<div class="pre">${nl(r.Finding)}</div>`,`<div class="pre">${nl(r.Immediate_Action)}</div>`,`<div class="pre">${nl(r.Preventive_Action)}</div>`,esc(r.Action_Owner),esc(r.Target_Date),r.Overdue_Flag==='YES'?badge('Overdue','critical'):badge('On time','good')]));}
function buildGap(data){const c=shell('gap-analysis.html','Gap Analysis','Weak KPI areas, gaps to target score 5, and likely root causes');c.innerHTML += `<div class="section grid two-col"><div class="card chart-card"><h2>Gap to 5 by KPI</h2><canvas id="gapChart"></canvas></div><div class="card chart-card"><h2>Root Cause Frequency</h2><canvas id="rootChart"></canvas></div></div><div class="section"><div id="gapTable"></div></div><div class="section"><div id="rootTable"></div></div>`;renderTable(document.getElementById('gapTable'),['KPI','Week Avg','Month Avg','Week Gap to 5','Month Gap to 5','Month Focus'],data.gapAnalysis.kpis.map(k=>[esc(k.label),num(k.weekAvg),num(k.monthAvg),num(k.weekGapTo5),num(k.monthGapTo5),(k.monthGapTo5>=2?badge('Immediate attention','critical'):badge('Monitor','warn'))]));renderTable(document.getElementById('rootTable'),['Root Cause','Count'],data.gapAnalysis.rootCauses.map(r=>[esc(r.rootCause),esc(r.count)]));new Chart(document.getElementById('gapChart'),{type:'bar',data:{labels:data.gapAnalysis.kpis.map(k=>k.label),datasets:[{label:'Month Gap to 5',data:data.gapAnalysis.kpis.map(k=>k.monthGapTo5)}]},options:{responsive:true,plugins:{legend:{labels:{color:'#dce9f7'}}},scales:{x:{ticks:{color:'#bfd2e9'}},y:{ticks:{color:'#bfd2e9'}}}}});new Chart(document.getElementById('rootChart'),{type:'doughnut',data:{labels:data.gapAnalysis.rootCauses.map(r=>r.rootCause),datasets:[{data:data.gapAnalysis.rootCauses.map(r=>r.count)}]},options:{responsive:true,plugins:{legend:{labels:{color:'#dce9f7'}}}}});}
function buildSchedules(data){const c=shell('schedules.html','April / May / June Schedules','All schedule sheets loaded from the workbook');const months=Object.keys(data.schedules);c.innerHTML += `<div class="tabs">${months.map((m,i)=>`<button class="tab ${i===0?'active':''}" data-month="${m}">${m}</button>`).join('')}</div><div id="scheduleContent"></div>`;const holder=document.getElementById('scheduleContent');function draw(month){document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.month===month));const matrix=data.schedules[month];holder.innerHTML=`<div class="table-wrap"><table>${matrix.map((r,ri)=>`<tr>${r.map(c=>ri===0?`<th>${esc(c??'')}</th>`:`<td>${esc(c??'')}</td>`).join('')}</tr>`).join('')}</table></div>`;}draw(months[0]);document.querySelectorAll('.tab').forEach(t=>t.addEventListener('click',()=>draw(t.dataset.month)));}
function buildRaw(data){const c=shell('raw-data.html','All Workbook Sheets','Every sheet from the Excel file is available here');const sheets=Object.keys(data.rawSheets);c.innerHTML += `<div class="tabs">${sheets.map((s,i)=>`<button class="tab ${i===0?'active':''}" data-sheet="${s}">${s}</button>`).join('')}</div><div id="sheetContent"></div>`;const holder=document.getElementById('sheetContent');function draw(name){document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.sheet===name));const matrix=data.rawSheets[name];holder.innerHTML=`<div class="table-wrap"><table>${matrix.map((r,ri)=>`<tr>${r.map(c=>ri===0?`<th>${esc(c??'')}</th>`:`<td>${esc(c??'')}</td>`).join('')}</tr>`).join('')}</table></div>`;}draw(sheets[0]);document.querySelectorAll('.tab').forEach(t=>t.addEventListener('click',()=>draw(t.dataset.sheet)));}
(async function(){const data=await loadData();const page=location.pathname.split('/').pop()||'index.html';if(page==='index.html')buildDashboard(data);else if(page==='inspections.html')buildInspections(data);else if(page==='capa.html')buildCapa(data);else if(page==='gap-analysis.html')buildGap(data);else if(page==='schedules.html')buildSchedules(data);else if(page==='raw-data.html')buildRaw(data);})();
